# Generated by Django 2.1.1 on 2018-09-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180907_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectskill',
            old_name='skill_id',
            new_name='skill',
        ),
    ]
