# Generated by Django 2.1.1 on 2018-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180907_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectskill',
            name='skill',
            field=models.IntegerField(default=1),
        ),
    ]
