# Generated by Django 2.1.1 on 2018-09-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180907_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectskill',
            name='text',
            field=models.TextField(default='hell'),
        ),
    ]
