# Generated by Django 2.1.1 on 2018-09-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_projectskill_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectskill',
            name='text',
        ),
    ]
