# Generated by Django 2.1.1 on 2018-09-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_projectskill_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectskill',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.Project'),
        ),
    ]
