# Generated by Django 2.1.1 on 2018-09-16 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.NewProject')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_receiver', to='api.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sender', to='api.User')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
