# Generated by Django 2.1.1 on 2018-09-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180916_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ('-timestamp',)},
        ),
    ]
